name: Compilación y pruebas con .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4 
      - name: Preparando .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restaurando dependencias
        run: dotnet restore
      - name: Compilando la solución
        run: dotnet build --no-restore --configuration Release
      - name: Ejecutando pruebas
        run: dotnet test --no-build --configuration Release
